on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

env:
  HOST: australia-southeast1-docker.pkg.dev
  REPO: armadaplatform/connect

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    env:
      image_url: australia-southeast1-docker.pkg.dev/armadaplatform/connect/${{ inputs.app }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
      - uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 #v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deploy
          SLACK_TITLE: Building ${{ inputs.app }}...
          SLACK_FOOTER: Sensium Labs
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 #v2.2.1
      - name: Login to Google Container Registry
        run: |
          echo "${{ secrets.GCLOUD_SERVICE_KEY }}" | base64 -d | docker login -u _json_key --password-stdin https://${{ env.HOST }}/
      # unfortunately we can't use deploy keys because the git config dance done by webfactory/ssh-agent happens in the runner
      # not in the docker container. Instead we use an SSH key on 'gpsengine-node' user and forward the access through to the
      # docker container with ssh-agent.
      - uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 #v0.7.0 (was v0.5.4)
        with:
            ssh-private-key: ${{ secrets.LIB_CLONE_KEY }}
      - name: Docker build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 #v3.2.0
        with:
          context: .
          push: true
          tags: ${{ env.image_url }}:${{ github.ref_name }},${{ env.image_url }}:latest
          cache-from: type=registry,ref=${{ env.image_url }}:latest
          cache-to: type=inline
          ssh: default=${{ env.SSH_AUTH_SOCK }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build-and-push
    steps:
      - name: Install SSH Client
      - uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 #v0.7.0 (was v0.5.4)
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_EDIT_KEY }}
      - uses: imranismail/setup-kustomize@6691bdeb1b0a3286fb7f70fd1423c10e81e5375f #v2.0.0 (was v1)
      - run: git clone git@github.com:gpsengine/ConnectProduction.git .
      - run: kustomize edit set image ${{ inputs.app }}=${{ env.IMAGE }}:${{ github.ref_name }}
        working-directory: ./app
      - run: git add .
      - run: |
          git config user.email "buildbot@gpsengine.github.com"
          git config user.name "$GITHUB_ACTOR"
      - run: git commit -m "Update ${{ inputs.app }}"
      - run: git push
      - uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7 #v2.2.0
        if: always()
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deploy
          SLACK_TITLE: ${{ inputs.app }} Complete
          SLACK_FOOTER: Sensium Labs

